inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'lokka.gemspec'
    - 'db/seeds.rb'

Style/Documentation:
  Enabled: false

Naming/MethodName:
  Exclude:
    - 'lib/lokka/models/**/*'

Naming/PredicateMethod:
  Exclude:
    - 'lib/lokka/helpers/helpers.rb'

Lint/MissingSuper:
  Exclude:
    - 'lib/lokka/models/entry.rb'
    - 'lib/lokka/models/site.rb'
    - 'lib/lokka/models/option.rb'
    - 'lib/lokka/helpers/helpers.rb'

Lint/UnreachableLoop:
  Exclude:
    - 'lib/lokka/importer.rb'

Style/MissingRespondToMissing:
  Exclude:
    - 'lib/lokka/models/entry.rb'
    - 'lib/lokka/models/site.rb'
    - 'lib/lokka/models/option.rb'
    - 'lib/lokka/helpers/helpers.rb'

Style/OpenStructUse:
  Exclude:
    - 'lib/lokka.rb'
    - 'lib/lokka/app/admin.rb'
    - 'lib/lokka/helpers/helpers.rb'

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space
  SpaceBeforeBlockParameters: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'test/**/*'

Lint/UselessAssignment:
  Exclude:
    - 'lib/lokka/helpers/helpers.rb'
    - 'public/theme/Farikal/config.rb'

Metrics/BlockLength:
  Exclude:
    - 'lokka.gemspec'
    - 'test/**/*'
    - 'lib/lokka/before.rb'
    - 'lib/lokka/app.rb'
    - 'lib/lokka/importer.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/lokka/app/entries.rb'
    - 'lib/lokka/app/admin.rb'
    - 'lib/lokka/models/entry.rb'
    - 'lib/lokka/migrator.rb'
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/lokka.rb'
    - 'lib/lokka/importer.rb'
    - 'lib/lokka/helpers/helpers.rb'
    - 'lib/lokka/before.rb'
    - 'lib/lokka/migrator.rb'
    - 'public/plugin/**/*'

Layout/LineLength:
  Exclude:
    - 'lokka.gemspec'
    - 'Gemfile'
    - 'public/**/*'
  AllowedPatterns:
    - '%r'
    - '%q'
    - '%Q'
    - '/\/.+\//'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/lokka.rb'
    - 'lib/lokka/before.rb'
    - 'lib/lokka/importer.rb'
    - 'lib/lokka/helpers/helpers.rb'
    - 'lib/lokka/migrator.rb'
    - 'public/plugin/**/*'
